name: c.e.faulkner
favicon: null
layout_spectrum: 0.25967
typography_spectrum: 0.27361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f1450'
    - '#624062'
    - '#63666f'
    - '#d0caca'
    - '#929197'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
